# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull
        run: |
          git pull origin master

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip3.8 install -r requirements.txt; fi

      - name: Restart PM2
        run: |
          pm2 restart app.py --interpreter=python3.8
